services:
    marttiphpbb.calendarinput.main_listener:
        class: marttiphpbb\calendarinput\event\main_listener
        arguments:
            - '@template'
            - '@language'
            - '@config'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.posting_listener:
        class: marttiphpbb\calendarinput\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@marttiphpbb.calendarinput.render.include_assets'
            - '@marttiphpbb.calendarinput.render.input_settings'
            - '@marttiphpbb.calendarinput.render.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.core.event_container:
        class: marttiphpbb\calendarinput\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarinput.timeformat:
        class: marttiphpbb\calendarinput\util\timeformat
        arguments:
            - '@user'

    marttiphpbb.calendarinput.render.include_assets:
        class: marttiphpbb\calendarinput\render\include_assets
        arguments:
            - '@marttiphpbb.calendarinput.repository.settings'
            - '@template'
            - '@language'
            - '%core.root_path%'

    marttiphpbb.calendarinput.render.input_settings:
        class: marttiphpbb\calendarinput\render\input_settings
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.render.posting:
        class: marttiphpbb\calendarinput\render\posting
        arguments:
            - '@marttiphpbb.calendarinput.repository.settings'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarinput.render.include_assets'

    marttiphpbb.calendarinput.dateformat:
        class: marttiphpbb\calendarinput\util\dateformat
        arguments:
            - '@user'
            - '@language'

    marttiphpbb.calendarinput.repository.settings:
        class: marttiphpbb\calendarinput\repository\settings
        arguments:
            - '@config_text'

